---
- hosts: all
  become: yes
  gather_facts: false
  tasks:
  - name: Install docker packages
    remote_user: root
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    tags:
      - docker
  - name: Add Docker s official GPG key
    remote_user: root
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    tags:
      - docker
  - name: Verify that we have the key with the fingerprint
    remote_user: root
    apt_key:
      id: 0EBFCD88
      state: present
    tags:
      - docker
  - name: Set up the stable repository
    remote_user: root
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present
      update_cache: yes
    tags:
      - docker
  - name: Update apt packages
    remote_user: root
    apt:
      update_cache: yes
    tags:
      - docker
  - name: Install docker
    remote_user: root
    apt:
      name: docker-ce
      state: present
      update_cache: yes
    #notify: Start docker on boot
    tags:
      - docker
  - name: Add remote "root" user to "docker" group
    remote_user: root
    user:
      name: "root"
      group: "docker"
      append: yes
    tags:
      - docker
  - name: Install docker-compose
    remote_user: root
    get_url:
      url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x' 


  - name: Copiar arquivo docker-compose.yml
      copy:
        dest: /opt/wordpress/docker-compose.yml
        content: |
          version: '3.1'

          services:
            db:
              image: mysql:5.7
              restart: always
              environment:
                MYSQL_ROOT_PASSWORD: rootpassword
                MYSQL_DATABASE: wordpress
                MYSQL_USER: wordpress
                MYSQL_PASSWORD: wordpresspassword
              volumes:
                - db_data:/var/lib/mysql

            wordpress:
              depends_on:
                - db
              image: wordpress:latest
              restart: always
              ports:
                - "8080:80"
              environment:
                WORDPRESS_DB_HOST: db:3306
                WORDPRESS_DB_USER: wordpress
                WORDPRESS_DB_PASSWORD: wordpresspassword
                WORDPRESS_DB_NAME: wordpress
              volumes:
                - wordpress_data:/var/www/html

            nginx:
              image: nginx:latest
              restart: always
              ports:
                - "80:80"
                - "443:443"
              volumes:
                - ./nginx.conf:/etc/nginx/nginx.conf

          volumes:
            db_data:
            wordpress_data:

    - name: Iniciar os containers do WordPress
      command:
        cmd: docker-compose up -d
        chdir: /opt/wordpress
